# Generated by Django 6.0.6 on 2026-06-30 11:42

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport.models.airplane_image_path),
        ),
        migrations.AddField(
            model_name='airport',
            name='image',
            field=models.ImageField(null=True, upload_to=airport.models.airport_image_path),
        ),
    ]
