# Generated by Django 6.0.6 on 2026-06-30 12:04

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_airplane_image_airport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airport.models.airplane_image_path),
        ),
        migrations.AlterField(
            model_name='airport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airport.models.airport_image_path),
        ),
    ]
