# Generated by Django 6.0.6 on 2026-06-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_alter_airplane_image_alter_airport_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='seats_in_rows',
            new_name='seats_in_row',
        ),
    ]
